### ISSUE TITLE
seems to have stopped working

### ISSUE THREAD

**Issue by azatoth** [dgbrt/explainXKCD_update#2]
Noticed the bot failed to create an entry for today. Looking at the code, and `curl -s http://www.xkcd.com` seems to fail load the webpage.

Perhaps using the json api might be better?

```perl
use LWP::Simple qw(get);
use JSON        qw(from_json);

my $url     = "https://xkcd.com/info.0.json";
my $decoded = from_json(get($url));

# Today $decoded is:
$decoded = {
    'alt'        => 'Texting should work. Unless the message is too long, in which case it gets converted to voicemails, and I think I\'m locked out of my voicemail.',
    'safe_title' => 'Phone Numbers',
    'month'      => '1',
    'title'      => 'Phone Numbers',
    'year'       => '2017',
    'img'        => 'http://imgs.xkcd.com/comics/phone_numbers.png',
    'day'        => '23',
    'news'       => '',
    'num'        => 1789,
    'transcript' => '',
    'link'       => ''
};
```

**Comment by dgbrt** [comment]
The problem was that the http-request now redirects to https but **curl** doesn't support this. This is fixed now.

The JSON page is nice but wasn't always reliable in the past. I prefer to parse the html page because that is what the user sees. Maybe I will add this code as a "backup". But when it says http for the image and that redirects to https we would have the same problem.
